#### general settings
name: medical_DDLS_setting1_x3
use_tb_logger: true
model: rrdb
distortion: sr
scale: 3
pca_matrix_path: /home/zmdz/name/szy/DCLS-SR-master/pca_matrix/DCLS/pca_matrix.pth
gpu_ids: [1]

degradation:
  random_kernel: True
  ksize: 21
  code_length: 10
  sig_min: 0.2
  sig_max: 3.0
  rate_iso: 1.0
  random_disturb: false

#### datasets
datasets:
  train:
    name: DIV2K
    mode: LQGTker
    dataroot_GT: /home/zmdz/DDSR-main/DDSR-main/DIV2K/DIV2K_HR_source.lmdb
    dataroot_LQ: /home/zmdz/DDSR-main/DDSR-main/DIV2K/Medical/LRblur_aniso/LRblur_aniso_x3.lmdb

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 32
    GT_size: 96
    LR_size: 32
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Set5
    mode: LQGT
    dataroot_GT: /home/zmdz/DDSR-main/DDSR-main/DIV2K/Axial_source.lmdb
    dataroot_LQ: /home/zmdz/DDSR-main/DDSR-main/DIV2K/Axialblur/LRblur_aniso/LRblur_aniso_x3.lmdb

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_E: !!float 4e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 500000
  warmup_iter: -1  # no warm up
  lr_steps: [100000, 400000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 0
  val_freq: !!float 2e3

#### logger
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 1e3
